name: supermarket_pos
description: A supermarket POS Flutter app.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.1.2
  path_provider: ^2.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
