name: supermarket_pos
description: A supermarket POS Flutter app.
publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.0" # رفع الإصدار الأدنى للـ SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^3.0.0 # استبدال الحزمة القديمة بالحزمة الجديدة
  http: ^1.4.0 # أحدث إصدار متوافق
  provider: ^6.1.3 # لإدارة الحالة إذا كنت بحاجة إليها

flutter:
  uses-material-design: true
